<?php
$available_blocks = $this->available_blocks;
$this->layout('layout/devcms/admin');
$this->placeholder('DevCms_AdminLayout_Title')->append('Content Block Admin');
$this->HeadTitle('Content Block Admin');
?>
<?php  if(count($available_blocks) === 0) { ?>
<div class="mdl-grid mdl-cell--12-col">
	<div class="mdl-color--white mdl-shadow--2dp mdl-cell mdl-cell--12-col">
		<div class="cell-padding">
			<p>There are no configured CMS content blocks to edit. Add them in the ZF2 config.</p>
		</div>
	</div>
</div>
<?php  } else { ?>
<table class="mdl-data-table mdl-js-data-table mdl-shadow--2dp" style="width:100%">
	<thead>
		<tr>
			<th class="mdl-data-table__cell--non-numeric">Label</th>
			<th class="mdl-data-table__cell--non-numeric">Actions</th>
		</tr>
	</thead>
	<tbody>
<?php 	foreach($available_blocks as $key => $label) { ?>
		<tr>
			<td class="mdl-data-table__cell--non-numeric"><?=$this->escapehtml($label)?></td>
			<td class="mdl-data-table__cell--non-numeric"><a href="<?=$this->url('devcms-admin/content-block/edit',['id'=>$key])?>">Edit</a></td>
		</tr>
<?php 	} ?>
	</tbody>
</table>
<?php  } ?>