<!doctype html>
<html >
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<?=$this->HeadTitle('DevCms')->setSeparator(' ::: ')?>
		<link href="https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en" rel="stylesheet">
		<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
		<link rel="stylesheet" href="https://storage.googleapis.com/code.getmdl.io/1.0.6/material.indigo-pink.min.css">
		<style><?include __DIR__ . '/styles.css'?></style>
		<?=$this->headlink()?>
		<?=$this->headstyle()?>
		<?=$this->headscript()?>
	</head>
	<body>
		<div class="demo-layout mdl-layout mdl-js-layout mdl-layout--fixed-drawer mdl-layout--fixed-header">
			<header class="demo-header mdl-layout__header mdl-color--grey-100 mdl-color-text--grey-600">
				<div class="mdl-layout__header-row">
					<span class="mdl-layout-title"><?=$this->placeholder('DevCms_AdminLayout_Title')->setSeparator(' / ')?></span>
				</div>
			</header>
			<div class="demo-drawer mdl-layout__drawer mdl-color--blue-grey-900 mdl-color-text--blue-grey-50">
				<header class="demo-drawer-header">
<!-- 					<img src="images/user.jpg" class="demo-avatar"> -->
					<div class="demo-avatar-dropdown">
						<span>hello@example.com</span>
						<div class="mdl-layout-spacer"></div>
						<button id="accbtn" class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--icon">
							<i class="material-icons" role="presentation">arrow_drop_down</i>
							<span class="visuallyhidden">Accounts</span>
						</button>
						<ul class="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect" for="accbtn">
							<li class="mdl-menu__item">hello@example.com</li>
							<li class="mdl-menu__item">info@example.com</li>
							<li class="mdl-menu__item"><i class="material-icons">add</i>Add another account...</li>
						</ul>
					</div>
				</header>
				<nav class="demo-navigation mdl-navigation mdl-color--blue-grey-800">
					<a class="mdl-navigation__link" href="<?=$this->url('devcms-admin')?>"><i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">home</i>Home</a>
					<a class="mdl-navigation__link" href="<?=$this->url('devcms-admin/content-block/list')?>"><i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">&#xE25E;</i>Content blocks</a>
					<a class="mdl-navigation__link" href="<?=$this->url('devcms-admin/page/list')?>"><i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">&#xE14D;</i>Pages</a>
					<a class="mdl-navigation__link" href=""><i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">&#xE899;</i>Authentication</a>
					<div class="mdl-layout-spacer"></div>
					<a class="mdl-navigation__link" href=""><i class="mdl-color-text--blue-grey-400 material-icons" role="presentation">help_outline</i><span class="visuallyhidden">Help</span></a>
				</nav>
			</div>
			<main class="mdl-layout__content mdl-color--grey-100">
				<div class="mdl-grid demo-content">
					<?=$this->content?>
				</div>
			</main>
		</div>
		<script src="https://storage.googleapis.com/code.getmdl.io/1.0.6/material.min.js"></script>
		<?=$this->inlinescript()?>
	</body>
</html>