<?php
/* @var $page \DevCms\Entity\PageEntity */
$page = $this->page;

/* @var $form \Zend\Form\Form */
$form = $this->form;

$this->layout('layout/devcms/admin');
$this->placeholder('DevCms_AdminLayout_Title')->append('Page Admin')->append('Edit Page');
$this->HeadTitle('Page Admin')->prepend('Edit "' . $page->label . '"');

$form->prepare();
?>
<a href="<?=$this->url('devcms-admin/page/list')?>" class="mdl-button mdl-js-button"><i class="material-icons">&#xE314;</i>Back to list</a>
<div class="mdl-grid mdl-cell--12-col">
	<div class="mdl-color--white mdl-shadow--2dp mdl-cell mdl-cell--12-col">
		<div class="cell-padding">
			<h2 class="mdl-typography--display-1"><?=$this->escapehtml($page->label)?></h2>
			<?=$this->form()->openTag($form)?>
			<?var_dump($form)?>
			<br />
			<br />
			<button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent">Save</button>
			<?=$this->form()->closeTag($form)?>
		</div>
	</div>
</div>
