<?php
/* @var $page \DevCms\Entity\PageEntity */
$page = $this->page;

/* @var $form \Zend\Form\Form */
$form = $this->form;

$this->Layout('layout/devcms/admin');
$this->Placeholder('DevCms_AdminLayout_Title')->append('Page Admin')->append('Edit Page');
$this->HeadTitle('Page Admin')->prepend('Edit "' . $page->label . '"');

$form->prepare();

/** @var \Zend\Form\Element $element */
?>
<a href="<?=$this->Url('devcms-admin/page/list')?>" class="mdl-button mdl-js-button"><i class="material-icons">&#xE314;</i>Back to list</a>
<div class="mdl-grid mdl-cell--12-col">
	<div class="mdl-color--white mdl-shadow--2dp mdl-cell mdl-cell--12-col">
		<div class="cell-padding">
			<?=$this->Form()->openTag($form)?>
				<div>
					<?=$this->FormRow($form->get('label'))?>
				</div>
				<div>
					<?=$this->FormRow($form->get('slug'))?>
				</div>
				<div>
					<?=$this->FormRow($form->get('layout'))?>
				</div>
<? foreach($form->get('vars')->getFieldsets() as $element) {?>
				<div>
					<?=$this->FormRow($element->get('id'))?>
<?php
	$e_content = $element->get('content');
	echo $this->Partial($e_content->getOption('__partial__'),['element'=>$e_content]);
?>
				</div>
<? } ?>
			<br />
			<br />
			<button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent">Save</button>
			<?=$this->Form()->closeTag($form)?>
		</div>
	</div>
</div>
