<?php
/**
 * @var $element \Zend\Form\Element
 */
$element = $this->element;
?>
<div style="margin-bottom: 16px;">
	<?=$this->FormLabel($element)?>
	<?=$this->FormTextarea($element)?>
</div>
<?php
$this->inlinescript()->appendFile('//cdn.tinymce.com/4/tinymce.min.js');
$this->inlinescript()
	->captureStart();
?>
document.addEventListener("DOMContentLoaded",function() {
	setTimeout(function() {
		tinymce.init({
			branding: false,
			selector: '#<?=$element->getAttribute('id')?>'
		});
	},10);
});
<?php $this->inlinescript()->captureEnd(); ?>